#!/usr/bin/env ruby

git_bundles = [ 
  "git://github.com/scrooloose/nerdtree.git",
  "git://github.com/tpope/vim-rails.git",
  "git://github.com/tpope/vim-surround.git",
  "git://github.com/tpope/vim-repeat.git",
  "git://github.com/tpope/vim-cucumber.git",
  "git://github.com/tsaleh/vim-supertab.git",
  "git://github.com/tsaleh/vim-tcomment.git",

  "git://github.com/tpope/vim-endwise.git",
  "git://github.com/kronn/vim-colorschemes.git",
  "git://github.com/Raimondi/delimitMate.git",
  "git://github.com/ajf/puppet-vim.git",
  "git://github.com/godlygeek/tabular.git",
  "git://github.com/tpope/vim-ragtag.git",

  "git://github.com/tpope/vim-rake.git",
  "git://github.com/tobiassvn/vim-gemfile.git",
  # "git://github.com/leshill/vim-json.git",
  "git://github.com/vim-ruby/vim-ruby.git",
  "git://github.com/vim-scripts/nginx.vim.git",

  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/mileszs/ack.vim.git",

  "git://github.com/nelstrom/vim-textobj-rubyblock.git",
    "git://github.com/kana/vim-textobj-user.git",

  "git://github.com/honza/snipmate-snippets.git",
    "git://github.com/garbas/vim-snipmate.git",
      "git://github.com/tomtom/tlib_vim.git",
      "git://github.com/MarcWeber/vim-addon-mw-utils.git",

  "git://github.com/gerw/vim-latex-suite.git",

  "git://github.com/tpope/vim-eunuch.git",
  "git://github.com/edsono/vim-dbext.git",

  "git://github.com/Lokaltog/vim-powerline.git",
  "git://github.com/timcharper/textile.vim.git",
]

git_bundles.each do |url|
  name = url.match(%r!.*/(.*)\.git!)[1]
  puts "git submodule add #{url} ~/.vim/bundle/#{name}"
end
