#!/usr/bin/env ruby

git_bundles = [ 
  "git://github.com/scrooloose/nerdtree.git",
  "git://github.com/tpope/vim-rails.git",
  "git://github.com/tpope/vim-surround.git",
  "git://github.com/tpope/vim-repeat.git",
  "git://github.com/tpope/vim-cucumber.git",
  "git://github.com/tsaleh/vim-supertab.git",
  "git://github.com/tsaleh/vim-tcomment.git",

  "git://github.com/tpope/vim-endwise.git",
  "git://github.com/kronn/vim-colorschemes.git",
  "git://github.com/Raimondi/delimitMate.git",
  "git://github.com/ajf/puppet-vim.git",
  "git://github.com/godlygeek/tabular.git",
  "git://github.com/tpope/vim-ragtag.git",

  "git://github.com/tpope/vim-rake.git",
  "git://github.com/tobiassvn/vim-gemfile.git",
  # "git://github.com/leshill/vim-json.git",
  "git://github.com/vim-ruby/vim-ruby.git",
  "git://github.com/vim-scripts/nginx.vim.git",

  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/mileszs/ack.vim.git",

  "git://github.com/nelstrom/vim-textobj-rubyblock.git",
    "git://github.com/kana/vim-textobj-user.git",

  "git://github.com/honza/snipmate-snippets.git",
    "git://github.com/garbas/vim-snipmate.git",
      "git://github.com/tomtom/tlib_vim.git",
      "git://github.com/MarcWeber/vim-addon-mw-utils.git",

  "git://github.com/gerw/vim-latex-suite.git",

  # "git://github.com/.git",
]

vim_org_scripts = [
  # ["IndexedSearch", "7062",  "plugin"],
  # ["gist",          "12732", "plugin"],
  # ["jquery",        "12107", "syntax"],
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "Trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "  Unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "  Downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end

