#!/bin/bash

function finish() {
  PREFIX=`git config gitflow.prefix.feature | sed 's!\/!\\\/!'`
  BRANCH=`git branch | grep '^*' | sed 's!\*\ !!'`
  FLOW_BRANCH=`echo $BRANCH | sed "s!$PREFIX!!"`

  if [ -n `echo $BRANCH | grep $PREFIX` ]; then
    echo "finishing $FLOW_BRANCH"
    git flow feature finish $FLOW_BRANCH
  fi
}

function review() {
  for COMMIT in `git log --reverse --format=format:%H ${1:-'develop...'}`; do
    clear
    git show $COMMIT
    read
  done
}

function changed_since() {
  git graph ${1}... --name-only | grep -v -e "^*" | sort -u
}
