#!/bin/bash

function finish() {
  PREFIX=`git config gitflow.prefix.feature`
  BRANCH=`git branch | grep '^*' | sed -e 's/\*\ //'`
  FLOW_BRANCH=`echo $BRANCH | sed "s/$PREFIX//"`

  if [ -n `echo $BRANCH | grep $PREFIX` ]; then
    echo "finishing $FLOW_BRANCH"
    git flow feature finish $FLOW_BRANCH
  fi
}
