#!/usr/bin/env bash

fliptable() {
  echo '（╯°□°）╯ ┻━┻'
} 

fliptwotables() {
  echo '┻━┻ ヽ(`Д´)ﾉ ┻━┻'
}

flipbouncingtables() {
  echo '（╯°□°）╯   ͡   ×   ͡   ×   ┻━┻'
}

shrug() {
  echo '¯\_(ツ)_/¯'
}
