#!/bin/bash

function remove_cache_files() {
  for FILE in {public/index.html,public/javascripts/all.js,public/stylesheets/all.css}; do
    touch $FILE;
    rm $FILE;
  done;
}

function clean_migration_files() {
  rm db/migrate/*.rb ; git co db/migrate/*.rb
}

function run_unittests() {
  ruby -rubygems -r 'test/unit' -e "require 'redgreen'; %w($@).each { |file| require %Q(test/unit/#{file}_test.rb) }"
}
