#!/bin/bash
# vim:ft=sh

# Subversion Functions
function svndiff() {
  # svn diff $@ | colordiff | less -R;
  # svn diff -x --ignore-all-space --no-diff-deleted --notice-ancestry $@ | colordiff | more;
  svn diff -x --ignore-all-space --no-diff-deleted --notice-ancestry $@ | colordiff;
}

function svnst() {
  svn st --ignore-externals -q $@;
}

function update_externals_to() {
  svn ps svn:externals "`svn pg svn:externals . | sed -E s/-r\([0-9]\+\)/-r$1/`" .
  echo "New Value:"
  echo "`svn pg svn:externals .`"
}

# function changes_since() {
#   svn log -r $1:HEAD -v -q | grep -E '^   [MA]' | sed 's/   [MA] \(.*\)$/\1/' | sort -u
# }
# function deleted_since() {
#   svn log -r $1:HEAD -v -q | grep -E '^   [D]' | sed 's/   [D] \(.*\)$/\1/' | sort -u
# }
# function log_since() {
#   svn log -r $1:HEAD | grep -E '^[^-r]'
# }
