#!/bin/bash

function main_terminal() {
  export PS1="Main Terminal $PS1"
  clear
  echo "This is the main Terminal of this X11 Session"
  echo "Due to the fantastic integration the whole Session"
  echo "is closed once this terminal window is closed."
  echo ""
}
