#!/bin/bash
# vim:ft=sh

# ls
alias ll="ls -l"
alias la="ls -a"
alias lla="ll -a"

# rails
alias td="tail -n 0 -f log/development.log"
alias tt="tail -n 0 -f log/test.log"

alias ss="script/server"
alias sc="script/console"
alias sd="script/dbconsole"
