#!/bin/bash
# vim:ft=sh

# enable color support
case `uname` in
  'Darwin')
    alias ls='ls -G'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
    ;;

  'Linux')
    if [ -x /usr/bin/dircolors ]; then
      test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
      alias ls='ls --color=auto'

      # grep colors
      alias grep='grep --color=auto'
      alias fgrep='fgrep --color=auto'
      alias egrep='egrep --color=auto'
    fi
    ;;
esac

# gnome
alias go='gnome-open'

# ls
alias la='ls -a'
alias ll="ls -l"
alias l="ll -h"

# rails
alias td="tail -n 0 -f log/development.log"
alias tt="tail -n 0 -f log/test.log"
alias tp="tail -n 0 -f log/production.log"

# rails 2 (rails 3 is good enough)
alias ss="script/server"
alias sc="script/console"
alias sd="script/dbconsole"
alias sg="script/generate"

# git convinience
alias homegit="GIT_DIR=~/Code/projects/dotfiles/.git GIT_WORK_TREE=~/ git"

# ssh
alias ssh="TERM=xterm ssh"

# various stuff
alias mmta="milkmaid task add"
# alias cuke="truncate --size 0 log/*.log; clear; KOPFLOS=no CAPYBARA_CHROME=yes bundle exec cucumber --drb -r features/"
alias cuke="truncate --size 0 log/*.log; clear; KOPFLOS=no CAPYBARA_CHROME=yes bundle exec cucumber -s -r features/"
